# Generated by cpp11: do not edit by hand

spr_encode_ <- function(n, k, x, y, extent) {
  .Call(`_spresslib_spr_encode_`, n, k, x, y, extent)
}

spr_decode_ <- function(n, k, h, extent) {
  .Call(`_spresslib_spr_decode_`, n, k, h, extent)
}
